kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: tim-service-pbhw
  namespace: tim-ns1
  labels:
    app: tim-app-pbhw
  annotations:
    openshift.io/host.generated: 'true'
spec:
  host: tim-service-pbhw-tim-ns1.apps.ocp22.4nrocket.com
  to:
    kind: Service
    name: tim-service-pbhw
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None