apiVersion: v1
kind: Service
metadata:
  name: tim-service-tomcat1
  namespace: ingress-nginx3
  labels:
    app: tim-app-tomcat1
spec:
  type: ClusterIP
  selector:
    app: tim-app-tomcat1
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
