apiVersion: v1
kind: Service
metadata:
  name: tim-service-alpine1
  namespace: ingress-nginx2
  labels:
    app: tim-app-alpine1
spec:
  type: ClusterIP
  selector:
    app: tim-app-alpine1
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
