apiVersion: v1
kind: Service
metadata:
  name: tim-service-f5hw
  namespace: tim-ns3
  labels:
    app: tim-app-f5hw
spec:
  type: ClusterIP
  selector:
    app: tim-app-f5hw
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
#
# NODEPORT   = PORT USED EXTERNALLY, LIKE IN THE BROWSER OR DNS
# PORT       = PORT USED INTERNALLY,
# TARGETPORT = PORT THAT CONTAINER IS LISTENING ON. 
#